"""empty message

Revision ID: 267d2e2f15e3
Revises: fdfecb9139a6
Create Date: 2024-02-06 19:05:11.243506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '267d2e2f15e3'
down_revision = 'fdfecb9139a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists_genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_uri', sa.String(length=37), nullable=True),
    sa.Column('artist_name', sa.String(length=50), nullable=True),
    sa.Column('artist_genres', sa.String(length=300), nullable=True),
    sa.Column('artist_main_genre', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_uri', sa.String(length=36), nullable=True),
    sa.Column('track_artist_main', sa.String(length=100), nullable=True),
    sa.Column('main_artist_uri', sa.String(length=37), nullable=True),
    sa.Column('track_artist_add1', sa.String(length=100), nullable=True),
    sa.Column('track_artist_add2', sa.String(length=100), nullable=True),
    sa.Column('track_title', sa.String(length=100), nullable=True),
    sa.Column('album_artist_main', sa.String(length=100), nullable=True),
    sa.Column('album_artist_add1', sa.String(length=100), nullable=True),
    sa.Column('album_artist_add2', sa.String(length=100), nullable=True),
    sa.Column('album_title', sa.String(length=100), nullable=True),
    sa.Column('album_uri', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_artists_genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_uri', sa.String(length=37), nullable=True),
    sa.Column('artist_main_genre_custom', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_playlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('playlist_id', sa.String(length=25), nullable=True),
    sa.Column('playlist_name', sa.String(length=100), nullable=True),
    sa.Column('is_owner', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_uri', sa.String(length=36), nullable=True),
    sa.Column('playlist_id_or_saved_song', sa.String(length=25), nullable=True),
    sa.Column('display_in_library', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_tracks')
    op.drop_table('users_playlists')
    op.drop_table('users_artists_genres')
    op.drop_table('tracks')
    op.drop_table('artists_genres')
    # ### end Alembic commands ###
