"""empty message

Revision ID: 2a1c4e2cfe94
Revises: 3cbc7cb78e5f
Create Date: 2024-03-26 11:43:55.447390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a1c4e2cfe94'
down_revision = '3cbc7cb78e5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_playlists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_in_library', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_playlists', schema=None) as batch_op:
        batch_op.drop_column('display_in_library')

    # ### end Alembic commands ###
