"""empty message

Revision ID: 3d9f47e5f987
Revises: b750fc7bfee7
Create Date: 2024-03-05 18:40:29.586453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d9f47e5f987'
down_revision = 'b750fc7bfee7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('no_of_songs_into_folder', sa.Integer(), nullable=True),
    sa.Column('include_songs_from_playlists', sa.Boolean(), nullable=True),
    sa.Column('include_followed_playlists', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_settings')
    # ### end Alembic commands ###
