"""empty message

Revision ID: 45ce6ddd927f
Revises: 267d2e2f15e3
Create Date: 2024-02-09 18:49:09.740253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45ce6ddd927f'
down_revision = '267d2e2f15e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_music_platform', schema=None) as batch_op:
        batch_op.drop_column('expires_in')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_music_platform', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_in', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
