"""empty message

Revision ID: 5572be67b5c2
Revises: 
Create Date: 2024-04-07 17:22:13.936359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5572be67b5c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_uri', sa.String(length=37), nullable=True),
    sa.Column('artist_name', sa.String(length=50), nullable=True),
    sa.Column('artist_genres', sa.String(length=300), nullable=True),
    sa.Column('artist_main_genre', sa.String(length=20), nullable=True),
    sa.Column('artist_subgenre', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artist_uri')
    )
    op.create_table('genres_subgenres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genre', sa.String(length=30), nullable=True),
    sa.Column('subgenre', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_uri', sa.String(length=36), nullable=True),
    sa.Column('track_artist_main', sa.String(length=100), nullable=True),
    sa.Column('main_artist_uri', sa.String(length=37), nullable=True),
    sa.Column('track_artist_add1', sa.String(length=100), nullable=True),
    sa.Column('track_artist_add2', sa.String(length=100), nullable=True),
    sa.Column('track_title', sa.String(length=100), nullable=True),
    sa.Column('album_artist_main', sa.String(length=100), nullable=True),
    sa.Column('album_artist_add1', sa.String(length=100), nullable=True),
    sa.Column('album_artist_add2', sa.String(length=100), nullable=True),
    sa.Column('album_title', sa.String(length=100), nullable=True),
    sa.Column('album_uri', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('track_uri')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=True),
    sa.Column('password', sa.String(length=60), nullable=True),
    sa.Column('account_created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('authenticated', sa.Boolean(), nullable=True),
    sa.Column('is_library_created', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('users_artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_uri', sa.String(length=37), nullable=True),
    sa.Column('artist_name', sa.String(length=50), nullable=True),
    sa.Column('artist_main_genre_custom', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('artist_subgenre_custom', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artist_uri'),
    sa.UniqueConstraint('artist_uri', 'user_id')
    )
    op.create_table('users_music_platform',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('music_platform_name', sa.String(length=15), nullable=True),
    sa.Column('music_platform_id', sa.String(length=40), nullable=True),
    sa.Column('access_token', sa.String(length=220), nullable=True),
    sa.Column('refresh_token', sa.String(length=131), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_playlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('playlist_id', sa.String(length=25), nullable=True),
    sa.Column('playlist_name', sa.String(length=100), nullable=True),
    sa.Column('is_owner', sa.Boolean(), nullable=True),
    sa.Column('display_in_library', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('playlist_id', 'user_id')
    )
    op.create_table('users_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('no_of_songs_into_folder', sa.Integer(), nullable=True),
    sa.Column('include_songs_from_playlists', sa.Boolean(), nullable=True),
    sa.Column('include_followed_playlists', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('users_tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_uri', sa.String(length=36), nullable=True),
    sa.Column('playlist_id_or_saved_song', sa.String(length=25), nullable=True),
    sa.Column('display_in_library', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_tracks')
    op.drop_table('users_settings')
    op.drop_table('users_playlists')
    op.drop_table('users_music_platform')
    op.drop_table('users_artists')
    op.drop_table('users')
    op.drop_table('tracks')
    op.drop_table('genres_subgenres')
    op.drop_table('artists')
    # ### end Alembic commands ###
