"""empty message

Revision ID: 5b22357ceb2c
Revises: 3d9f47e5f987
Create Date: 2024-03-13 13:03:04.720116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b22357ceb2c'
down_revision = '3d9f47e5f987'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_uri', sa.String(length=37), nullable=True),
    sa.Column('artist_name', sa.String(length=50), nullable=True),
    sa.Column('artist_genres', sa.String(length=300), nullable=True),
    sa.Column('artist_main_genre', sa.String(length=20), nullable=True),
    sa.Column('artist_subgenre', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artist_uri')
    )
    op.create_table('users_artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_uri', sa.String(length=37), nullable=True),
    sa.Column('artist_name', sa.String(length=50), nullable=True),
    sa.Column('artist_main_genre_custom', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('artist_subgenre_custom', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artist_uri')
    )
    op.drop_table('users_artists_genres')
    op.drop_table('artists_genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists_genres',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('artist_uri', sa.VARCHAR(length=37), autoincrement=False, nullable=True),
    sa.Column('artist_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('artist_genres', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('artist_main_genre', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('artist_subgenre', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='artists_genres_pkey'),
    sa.UniqueConstraint('artist_uri', name='artists_genres_artist_uri_key')
    )
    op.create_table('users_artists_genres',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('artist_uri', sa.VARCHAR(length=37), autoincrement=False, nullable=True),
    sa.Column('artist_main_genre_custom', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('artist_subgenre_custom', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='users_artists_genres_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='users_artists_genres_pkey'),
    sa.UniqueConstraint('artist_uri', name='users_artists_genres_artist_uri_key')
    )
    op.drop_table('users_artists')
    op.drop_table('artists')
    # ### end Alembic commands ###
