"""empty message

Revision ID: 68001eddb050
Revises: 5b22357ceb2c
Create Date: 2024-03-15 21:50:51.913454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68001eddb050'
down_revision = '5b22357ceb2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_artists', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['artist_uri', 'user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_artists', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
