"""empty message

Revision ID: 8878e9a6c9a2
Revises: c0652b90cb4f
Create Date: 2024-02-19 15:32:06.554091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8878e9a6c9a2'
down_revision = 'c0652b90cb4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres_subgenres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genre', sa.String(length=30), nullable=True),
    sa.Column('subgenre', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artists_genres', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist_subgenre', sa.String(length=30), nullable=True))

    with op.batch_alter_table('users_artists_genres', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist_subgenre_custom', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_artists_genres', schema=None) as batch_op:
        batch_op.drop_column('artist_subgenre_custom')

    with op.batch_alter_table('artists_genres', schema=None) as batch_op:
        batch_op.drop_column('artist_subgenre')

    op.drop_table('genres_subgenres')
    # ### end Alembic commands ###
