"""empty message

Revision ID: 9b877092bfb6
Revises: 14ca48b2c22c
Create Date: 2024-04-02 17:10:53.812315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b877092bfb6'
down_revision = '14ca48b2c22c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_music_platform', schema=None) as batch_op:
        batch_op.alter_column('music_platform_id',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=40),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_music_platform', schema=None) as batch_op:
        batch_op.alter_column('music_platform_id',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)

    # ### end Alembic commands ###
