"""empty message

Revision ID: b750fc7bfee7
Revises: 8878e9a6c9a2
Create Date: 2024-02-20 14:21:09.573232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b750fc7bfee7'
down_revision = '8878e9a6c9a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_library_created', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_library_created')

    # ### end Alembic commands ###
