"""empty message

Revision ID: c0652b90cb4f
Revises: 45ce6ddd927f
Create Date: 2024-02-13 21:35:17.624502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0652b90cb4f'
down_revision = '45ce6ddd927f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artists_genres', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['artist_uri'])

    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['track_uri'])

    with op.batch_alter_table('users_artists_genres', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['artist_uri'])

    with op.batch_alter_table('users_playlists', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['playlist_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_playlists', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('users_artists_genres', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('artists_genres', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
