"""empty message

Revision ID: feb4759135c2
Revises: 5572be67b5c2
Create Date: 2024-04-11 15:41:31.977747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feb4759135c2'
down_revision = '5572be67b5c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_music_platform', schema=None) as batch_op:
        batch_op.alter_column('access_token',
               existing_type=sa.VARCHAR(length=220),
               type_=sa.String(length=270),
               existing_nullable=True)
        batch_op.alter_column('refresh_token',
               existing_type=sa.VARCHAR(length=131),
               type_=sa.String(length=150),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_music_platform', schema=None) as batch_op:
        batch_op.alter_column('refresh_token',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=131),
               existing_nullable=True)
        batch_op.alter_column('access_token',
               existing_type=sa.String(length=270),
               type_=sa.VARCHAR(length=220),
               existing_nullable=True)

    # ### end Alembic commands ###
