"""empty message

Revision ID: 91365ae9166d
Revises: 
Create Date: 2024-01-13 13:40:05.077626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91365ae9166d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=30), nullable=True),
    sa.Column('account_created', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('users_music_platform',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('music_platform_name', sa.String(length=15), nullable=True),
    sa.Column('music_platform_id', sa.String(length=15), nullable=True),
    sa.Column('access_token', sa.String(length=220), nullable=True),
    sa.Column('expires_in', sa.Integer(), nullable=True),
    sa.Column('refresh_token', sa.String(length=131), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_music_platform')
    op.drop_table('users')
    # ### end Alembic commands ###
